### ISSUE TITLE
[FR] Add to `quicklisp`

### ISSUE THREAD

**Issue by NightMachinery** [Zulu-Inuoe/jzon#10]

**Comment by Zulu-Inuoe** [comment]
Hi @NightMachinary . I appreciate the support, unfortunately I'd like to avoid putting this on Quicklisp until it's more complete. At a minimum I wish to have:
1. A roundtripping reader/writer (output JSON exactly as it was read)
2. Object coercion mechanism for reading (eg read JSON as a CL class/structure)

Until these are done, I don't want to pollute QL with yet another JSON library.

**Comment by fukamachi** [comment]
+1 for adding to Quicklisp.
IMHO, jzon is already the best JSON library for rendering JSON views in web app.
So, I'd like to switch from Jonathan in my libraries, but can't because jzon is not in Quicklisp.

**Comment by Zulu-Inuoe** [comment]
@fukamachi Thanks for the support. 
Unfortunately I haven't been doing much programming in my free time as of late.
But if you think the library is useful as-is, then it's fair to add it to quicklisp, and I can add my other desired features over time as I can.

I just don't want to continue to contribute to the 100 JSON library meme on Quicklisp unless I offer some substantial benefit

**Comment by Valera** [comment]
@Zulu-Inuoe I think that jzon is a new generation JSON parser taking into account advantages and disadvantages of previous generation of parsers. And it has full coverage of JSON standard verified by third-party test suite. This is already good reasons for releasing v1 on quicklisp.

**Comment by K1D77A** [comment]
Yes, can you please add this to quicklisp, the pretty print feature is exceptionally useful :)

**Comment by Shinmera** [comment]
Throwing my hat into the pile. I'd like to start using this.

**Comment by phoe** [comment]
Pretty please?

**Comment by Zulu-Inuoe** [comment]
Oh my gosh. Let me see what I can do this weekend and I'll add v1 on Monday no matter what

**Comment by Zulu-Inuoe** [comment]
haha jk did I say that weekend? I meant this one.

In all seriousness I've been doing some work and thinking over the week and will definitely have something solid here soon.
Thanks all

**Comment by phoe** [comment]
![fbn7krvnq8381](https://user-images.githubusercontent.com/15045546/176945689-8e697c26-8a9c-424d-b6a5-e8f726103896.jpg)

**Comment by Zulu-Inuoe** [comment]
> ![fbn7krvnq8381](https://user-images.githubusercontent.com/15045546/176945689-8e697c26-8a9c-424d-b6a5-e8f726103896.jpg)

Unfortunately I am a busy tortoise :(

**Comment by phoe** [comment]
Do you need any support with that - as in, what would happen ~~to me~~ if I did things the naïve way and made a quicklisp-projects issue pointing to the current master branch?

**Comment by Zulu-Inuoe** [comment]
I honestly don't remember the status of what things are WIP. I believe there's still a couple of issues with `stringify`, including the floating point printer, the string replacer, and the auto-coercion stuff in general.
As before it's ultimately: I still don't know if it offers anything truly above and beyond the other json libs on QL already.

The other issue is that if we make available a beta version as-is, it'll be hard to fix things without breaking users - the auto-coercion stuff especially scares me.

**Comment by Zulu-Inuoe** [comment]
Alright this is actually finally happening. All my remaining stuff for v1 are resolved and I've decided what to leave out for a v2.

Code-wise, the true final final stuff is whether or not I keep the alist/plist heuristics in `write-value` which I am awaiting review.
The other changes are things I can do without breaking backwards-compat, like updating docs and optimizing my string-on-string parser

**Comment by Zulu-Inuoe** [comment]
https://github.com/quicklisp/quicklisp-projects/issues/2256

**Comment by fukamachi** [comment]
Great, thank you!

**Comment by phoe** [comment]
Added and available; huge thanks! I think this issue can now be closed.

**Comment by Zulu-Inuoe** [comment]
Thanks for the heads up, @phoe
