### ISSUE TITLE
Custom stringify

### ISSUE THREAD

**Issue by Mark-Boger** [Zulu-Inuoe/jzon#2]
One thing that I think that [jonathan](https://github.com/Rudolph-Miller/jonathan) has over this library is the custom `to-json` methods. While the current `stringify` is a great default I find that sometimes I need to be able to leave slots out for client programs, either because they don't need or shouldn't have some information. Are there plans to implement something like this?

**Comment by Mark-Boger** [comment]
Never mind, I didn't realize that the `coerced-fields` is what I was looking for

**Comment by Zulu-Inuoe** [comment]
Hey @Mark-Boger appreciate the feedback ! And yes, specializing `jzon:coerced-fields` currently is the most straightforward way of getting custom serialization.

I'm still toying around with both custom serialize/deserialize, from API design and even naming of functions - eg I am by no means married to `stringify`.
So if you have any thoughts on the design of this, please feel free to share them.

Thanks!
