### ISSUE TITLE
FLOAT-FEATURES is loaded in a really desperate manner

### ISSUE THREAD

**Issue by phoe** [Zulu-Inuoe/jzon#26]
https://github.com/Zulu-Inuoe/jzon/blob/90c9eed6f4b4efaa290ce1d5fc763b8aa6e2a9db/src/eisel-lemire.lisp#L1-L11

This block of code is maybe superfluous because ASDF should take care of this: see the dependency at https://github.com/Zulu-Inuoe/jzon/blob/90c9eed6f4b4efaa290ce1d5fc763b8aa6e2a9db/src/com.inuoe.jzon.asd#L8

**Comment by Zulu-Inuoe** [comment]
FYI this just made it simpler for me when developing to test different optimization levels as I could single-load this file and `float-features`
It doesn't affect anything when the system's loaded through ASDF
