### ISSUE TITLE
FLOAT-FEATURES are loaded in a very very dramatic manner

### ISSUE THREAD

**Issue by phoe** [Zulu-Inuoe/jzon#28]
https://github.com/Zulu-Inuoe/jzon/blob/90c9eed6f4b4efaa290ce1d5fc763b8aa6e2a9db/src/eisel-lemire.lisp#L1-L11

Isn't an ASDF dependency on `float-features` enough?

**Comment by Zulu-Inuoe** [comment]
That won't do anything when loaded through ASDF. It just made it easier to test the code on different optimization settings etc

**Comment by phoe** [comment]
wait did I really open two issues for that? aaaa I'm sorry I only meant to make one of them
