### ISSUE TITLE
quicklisp's jzon does not compile in allegro common lisp

### ISSUE THREAD

**Issue by MauDagos** [Zulu-Inuoe/jzon#40]
The current version of jzon in quicklisp does not compile in allegro common lisp. This is the error I get:

```
Attempt to take the value of the unbound variable `+%POW10-MIN+'.
```

However, compiling the tip of `master` from source runs just fine. Would it possible to update the version of jzon in quicklisp?

Thanks in advance!

**Comment by Zulu-Inuoe** [comment]
Hey, thanks for checking.
Quicklisp updates at a roughly monthly cadence, so that'll be fixed next release.

**Comment by Zulu-Inuoe** [comment]
Closing this issue now that I've merged the changes to main. It'll be fixed next Quicklisp release, or you can use the latest release on Ultralisp
