### ISSUE TITLE
Control stack exhausted while reading json from stream

### ISSUE THREAD

**Issue by solanav** [Zulu-Inuoe/jzon#65]
![imagen](https://github.com/Zulu-Inuoe/jzon/assets/32469597/cc87afbe-ae6f-4f51-a1fc-ffd3389bcad1)
 
The file I'm reading (4.5M of size) contains very long lists of objects. Maybe that's whats causing it, I'll try to reproduce with a generated JSON because I can't share the one that's causing problems.

This is happening inside roswell with version 2.4.5 of SBCL.

If I run it in SBCL raw in debian (1.4.16.debian) it doesn't seem to happen.

**Comment by Zulu-Inuoe** [comment]
It would be helpful to have your test data, since even with deep nesting, you shouldn't be receiving this error.
Could you also confirm the version of jzon on the environment that it's crashing? You can find this at the repl with
```lisp
(asdf:system-version (asdf:find-system '#:com.inuoe.jzon))
```

**Comment by solanav** [comment]
I was using version `1.1.2`, on the latest version `1.1.3` it gives me a "Encountered end of input inside string constant" which I guess means this is a me-problem.

**Comment by Zulu-Inuoe** [comment]
Is it valid JSON that I'm incorrectly erroring on, since Yason parses it? Would you be able to share the input file?

**Comment by solanav** [comment]
Sorry for the delay, the file contains confidential info about my employer so I had to randomize the data. [Here](https://gist.github.com/solanav/a4fdb1d60f3861a845e8f9a501eb9fc2) you can see the file that causes the bug. Just tried it on `1.1.2` with SBCL `2.4.5`.

![image](https://github.com/Zulu-Inuoe/jzon/assets/32469597/d99d0b1e-6b84-49bc-9cb2-b106e85dd483)

**Comment by Zulu-Inuoe** [comment]
No worries. Thanks for providing that

**Comment by Zulu-Inuoe** [comment]
FYI it looks like it loads fine on latest jzon (1.1.4). Looking at the changelog, that was fixed in 1.1.3. Specifically this commit: 67c0411916222f5efbadcb47b7e9bc0a12297780

**Comment by Zulu-Inuoe** [comment]
I'm going to close this issue as fixed and recommend readers to upgrade to latest, and apologize for that bug!
